# Generated by Django 3.2.3 on 2021-06-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='Phone_Number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
