# Generated by Django 3.2.3 on 2021-06-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguidance', '0003_career_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='Message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
