# Generated by Django 3.2.3 on 2021-06-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguidance', '0005_career_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='Branch',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
