# Generated by Django 3.2.3 on 2021-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguidance', '0006_career_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='Enrollment_no',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
